application: <application>
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /.*
  script: xmpprpc.py
  login: admin

inbound_services:
- xmpp_message
- xmpp_presence

